name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'index.html'  # Solo ejecuta el workflow si este archivo cambia

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write # Otorga permisos de escritura al GITHUB_TOKEN para desplegar en GitHub Pages
      id-token: write # Necesario para la autenticación OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@vlatest

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@vlatest # Esto configura el entorno de GitHub Pages

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@vlatest
        with:
          # Ruta a tus archivos estáticos (donde está index.html)
          # Si index.html está en la raíz de tu repo, usa '.'
          # Si está en una carpeta 'docs', usa './docs'
          path: '.'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@vlatest # Esto despliega tu artefacto a GitHub Pages